apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizationmicroservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthorizationMicroService
  template:
    metadata:
      labels:
        app: AuthorizationMicroService
    spec:
      containers:
      - name: retailauthrepos
        image: productcr.azurecr.io/retailauthrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: productsn

---
apiVersion: v1
kind: Service
metadata:
  name: authorizationmicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuthorizationMicroService